import type { ContentType } from "./types";

export type ContentConfig = {
  cardTitle: string;
  description: string;
  detailLabel: string;
  detailPlaceholder: string;
  firstSceneLabel: string;
  firstScenePlaceholder: string;
  iconLabel: string;
  messageLabel: string;
  messagePlaceholder: string;
  primaryQuestion: string;
  primaryPlaceholder: string;
  relationshipLabel: string;
  relationshipPlaceholder: string;
  resultLabel: string;
};

export const contentConfigs: Record<ContentType, ContentConfig> = {
  family_memory: {
    cardTitle: "가족에게 남기는 이야기",
    description: "부모님, 배우자, 자녀, 친구에게 전하고 싶은 마음을 기록합니다.",
    detailLabel: "이야기를 남기는 사람",
    detailPlaceholder: "예: 나",
    firstSceneLabel: "가장 먼저 떠오르는 장면",
    firstScenePlaceholder: "예: 비 오는 날 우산을 씌워주던 모습",
    iconLabel: "가족",
    messageLabel: "아직 마음에 남아 있는 말",
    messagePlaceholder: "예: 정말 고마웠어요",
    primaryQuestion: "오늘 떠올리고 싶은 사람은 누구인가요?",
    primaryPlaceholder: "예: 엄마",
    relationshipLabel: "그 사람은 나에게",
    relationshipPlaceholder: "예: 어머니, 배우자, 친구",
    resultLabel: "편지, 기억 카드, Memory Vault 저장",
  },
  future_self: {
    cardTitle: "미래의 나에게",
    description: "몇 년 뒤의 나에게 지금의 고민, 꿈, 약속을 남깁니다.",
    detailLabel: "오늘의 나",
    detailPlaceholder: "예: 2026년의 나",
    firstSceneLabel: "지금 가장 중요하게 생각하는 것",
    firstScenePlaceholder: "예: 가족과 일을 오래 지키는 것",
    iconLabel: "미래",
    messageLabel: "미래의 나에게 해주고 싶은 말",
    messagePlaceholder: "예: 너무 조급해하지 않았으면 좋겠어",
    primaryQuestion: "미래의 나에게 어떤 시간을 남기고 싶나요?",
    primaryPlaceholder: "예: 10년 뒤의 나",
    relationshipLabel: "이 기록의 의미",
    relationshipPlaceholder: "예: 나에게 보내는 타임캡슐",
    resultLabel: "타임캡슐 편지, 미래 공개 링크, Memory Vault 저장",
  },
  parent_life_book: {
    cardTitle: "부모님의 인생책",
    description: "어린 시절부터 행복했던 순간까지 부모님의 삶을 차곡차곡 기록합니다.",
    detailLabel: "기록을 돕는 사람",
    detailPlaceholder: "예: 아들 민준",
    firstSceneLabel: "가장 먼저 듣고 싶은 이야기",
    firstScenePlaceholder: "예: 어린 시절 살던 동네 이야기",
    iconLabel: "인생책",
    messageLabel: "꼭 남기고 싶은 질문",
    messagePlaceholder: "예: 가장 행복했던 순간은 언제였나요?",
    primaryQuestion: "오늘 누구의 삶을 기록하고 싶나요?",
    primaryPlaceholder: "예: 아버지",
    relationshipLabel: "그분은 나에게",
    relationshipPlaceholder: "예: 아버지, 어머니",
    resultLabel: "인생책 초안, 기억 카드, 영상 기록",
  },
  couple_time_capsule: {
    cardTitle: "커플 타임캡슐",
    description: "처음 만난 날, 가장 행복했던 순간, 앞으로의 약속을 보관합니다.",
    detailLabel: "기록을 남기는 사람",
    detailPlaceholder: "예: 우리",
    firstSceneLabel: "가장 먼저 떠오르는 순간",
    firstScenePlaceholder: "예: 처음 만난 카페",
    iconLabel: "커플",
    messageLabel: "앞으로의 약속",
    messagePlaceholder: "예: 오래 서로의 편이 되어주자",
    primaryQuestion: "이 기록을 함께 남기고 싶은 사람은 누구인가요?",
    primaryPlaceholder: "예: 지민",
    relationshipLabel: "우리의 관계",
    relationshipPlaceholder: "예: 연인, 부부",
    resultLabel: "기념일 공개, 영상, 편지",
  },
  kpop_recording: {
    cardTitle: "나만의 킬링보이스 만들기",
    description: "나만의 목소리와 노래에 얽힌 기억을 기록합니다.",
    detailLabel: "기록하는 사람",
    detailPlaceholder: "예: 민준",
    firstSceneLabel: "선택한 노래",
    firstScenePlaceholder: "예: 오래 좋아했던 발라드",
    iconLabel: "음악",
    messageLabel: "이 노래와 관련된 기억",
    messagePlaceholder: "예: 힘들 때마다 들었던 노래예요",
    primaryQuestion: "오늘 어떤 노래를 기록하고 싶나요?",
    primaryPlaceholder: "예: 내 인생곡",
    relationshipLabel: "이 노래의 의미",
    relationshipPlaceholder: "예: 위로, 고백, 추억",
    resultLabel: "음원 기록, 영상 기록, 커버 이미지",
  },
  live_performance: {
    cardTitle: "라이브 공연 기록",
    description: "연주와 공연의 순간을 인터뷰와 함께 아카이브합니다.",
    detailLabel: "공연자 또는 팀",
    detailPlaceholder: "예: 민준 밴드",
    firstSceneLabel: "공연 소개",
    firstScenePlaceholder: "예: 첫 단독 공연",
    iconLabel: "공연",
    messageLabel: "관객에게 남기고 싶은 말",
    messagePlaceholder: "예: 이 순간을 함께해줘서 고마워요",
    primaryQuestion: "오늘 어떤 공연을 기록하고 싶나요?",
    primaryPlaceholder: "예: 첫 라이브 공연",
    relationshipLabel: "공연의 성격",
    relationshipPlaceholder: "예: 단독 공연, 졸업 공연",
    resultLabel: "공연 아카이브, 영상 기록",
  },
  artist_interview: {
    cardTitle: "아티스트 인터뷰",
    description: "음악을 시작한 이유와 앞으로 남기고 싶은 이야기를 기록합니다.",
    detailLabel: "아티스트 이름",
    detailPlaceholder: "예: 송민준",
    firstSceneLabel: "가장 의미 있는 곡",
    firstScenePlaceholder: "예: 처음 만든 자작곡",
    iconLabel: "아티스트",
    messageLabel: "앞으로 남기고 싶은 이야기",
    messagePlaceholder: "예: 내 음악이 누군가에게 작은 힘이 되었으면 해요",
    primaryQuestion: "오늘 어떤 음악 이야기를 남기고 싶나요?",
    primaryPlaceholder: "예: 나의 첫 앨범",
    relationshipLabel: "음악과 나의 관계",
    relationshipPlaceholder: "예: 삶의 기록, 위로",
    resultLabel: "인터뷰 기록, 영상, Memory Vault 저장",
  },
  founder_story: {
    cardTitle: "창업자의 이야기",
    description: "창업의 이유, 버틴 순간, 후배에게 남길 말을 보관합니다.",
    detailLabel: "창업자 이름",
    detailPlaceholder: "예: 송민준",
    firstSceneLabel: "창업을 결심한 순간",
    firstScenePlaceholder: "예: 첫 고객을 만난 날",
    iconLabel: "창업",
    messageLabel: "후배에게 남기고 싶은 말",
    messagePlaceholder: "예: 버티되, 혼자 버티지는 말라고 말하고 싶어요",
    primaryQuestion: "오늘 어떤 창업 이야기를 남기고 싶나요?",
    primaryPlaceholder: "예: 첫 회사의 시작",
    relationshipLabel: "이 기록의 대상",
    relationshipPlaceholder: "예: 후배 창업자, 팀원, 가족",
    resultLabel: "창업자 기록, 기업 타임캡슐, 미래 공개 링크",
  },
  korea_trip: {
    cardTitle: "한국 여행 기록",
    description: "한국에서의 여행, 사진, 목소리, 감정을 하나의 기록으로 남깁니다.",
    detailLabel: "기록하는 사람",
    detailPlaceholder: "예: Alex",
    firstSceneLabel: "기억하고 싶은 여행 순간",
    firstScenePlaceholder: "예: 한강에서 보낸 밤",
    iconLabel: "여행 기록",
    messageLabel: "언젠가 공유하고 싶은 사람",
    messagePlaceholder: "예: 가족에게 이 여행을 보여주고 싶어요",
    primaryQuestion: "한국에서 어떤 기억을 남기고 싶나요?",
    primaryPlaceholder: "예: 서울에서의 첫 여행",
    relationshipLabel: "여행의 의미",
    relationshipPlaceholder: "예: 혼자 떠난 여행, 가족 여행",
    resultLabel: "여행 인터뷰, 여행 기억 카드, 여행 요약, Memory Vault 저장",
  },
  kpop_experience: {
    cardTitle: "K-POP 녹음 체험",
    description: "좋아하는 K-POP 노래를 스튜디오 분위기에서 직접 녹음하고 기록합니다.",
    detailLabel: "기록하는 사람",
    detailPlaceholder: "예: Mina",
    firstSceneLabel: "녹음하고 싶은 노래",
    firstScenePlaceholder: "예: 좋아하는 K-POP 곡",
    iconLabel: "녹음 체험",
    messageLabel: "이 노래와 연결된 기억",
    messagePlaceholder: "예: 한국 여행 중 계속 들었던 노래",
    primaryQuestion: "오늘 어떤 노래를 기록하고 싶나요?",
    primaryPlaceholder: "예: 내 여행의 OST",
    relationshipLabel: "이 노래의 의미",
    relationshipPlaceholder: "예: 설렘, 위로, 여행",
    resultLabel: "음원 기록, 커버 이미지, 짧은 영상 기록, Memory Vault 저장",
  },
  kdrama_message: {
    cardTitle: "K-드라마 메시지 씬",
    description: "드라마 속 한 장면처럼 사랑, 감사, 이별, 응원의 메시지를 영상으로 남깁니다.",
    detailLabel: "메시지를 남기는 사람",
    detailPlaceholder: "예: Alex",
    firstSceneLabel: "남기고 싶은 감정",
    firstScenePlaceholder: "예: 고마움, 응원, 사랑",
    iconLabel: "메시지 대상",
    messageLabel: "영상에 담고 싶은 말",
    messagePlaceholder: "예: 늘 내 편이 되어줘서 고마워",
    primaryQuestion: "이 메시지는 누구에게 남기고 싶나요?",
    primaryPlaceholder: "예: 나의 친구",
    relationshipLabel: "메시지의 성격",
    relationshipPlaceholder: "예: 사랑, 감사, 사과, 응원",
    resultLabel: "메시지 영상, 자막 카드, Memory Vault 저장",
  },
  seoul_night_letter: {
    cardTitle: "서울 밤 편지",
    description: "서울에서의 밤, 오늘의 감정과 여행의 기억을 미래의 나 또는 누군가에게 남깁니다.",
    detailLabel: "편지를 남기는 사람",
    detailPlaceholder: "예: Alex",
    firstSceneLabel: "오늘 서울에서 남은 장면",
    firstScenePlaceholder: "예: 남산에서 본 야경",
    iconLabel: "편지를 받을 사람",
    messageLabel: "오늘 밤 남기고 싶은 말",
    messagePlaceholder: "예: 이 밤을 오래 기억하고 싶어",
    primaryQuestion: "서울의 오늘 밤을 누구에게 남기고 싶나요?",
    primaryPlaceholder: "예: 미래의 나",
    relationshipLabel: "편지의 방향",
    relationshipPlaceholder: "예: 미래의 나, 가족, 친구",
    resultLabel: "감성 편지, 여행 기록 카드, 미래 공개 링크",
  },
};

export function getContentConfig(type: ContentType) {
  return contentConfigs[type];
}
